# Generated by Django 2.2.3 on 2019-07-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'Address_Info',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyWebsite', models.CharField(max_length=50)),
                ('companyEmail', models.CharField(max_length=50)),
                ('landline', models.IntegerField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='firstapp.Address')),
            ],
            options={
                'db_table': 'Company_Info',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeEmail', models.CharField(max_length=50)),
                ('employeename', models.CharField(max_length=50)),
                ('employeecontact', models.IntegerField()),
                ('employeeage', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='firstapp.Company')),
                ('empaddress', models.ManyToManyField(to='firstapp.Address')),
            ],
            options={
                'db_table': 'Employee_Info',
            },
        ),
    ]
